class Filenames:
    PIER = "pier"
    ABUT = "abut"
    INDIV = "indiv"
    COMMON = "common"
    INPUT = "input"
    OUTPUT = "output"
    LOCAL = "local"
    WORLD = "world"
    COLUMN = "column"
    BARRIER = "barrier"
    BASE_POINT = "base_point"
    SUPERSTRUCTURE = "superstructure"
    SUBSTRUCTURE = "substructure"
    COORDS = "coords"
    SLAB = "slab"
    MG = "main_girder"
    UP = "up"
    DOWN = "down"
    TOP_POINTS = "top_points"
    CENTER = "center"
    ADDITONAL_POINTS = "additional"
    CENTER_POINTS = "center_points"
    BOTTOM_POINTS = "bottom_points"

