class Filenames:
    PIER = "pier"
    ABUT = "abut"
    INDIV = "indiv"
    COMMON = "common"
    INPUT = "input"
    OUTPUT = "output"
    LOCAL = "local"
    WORLD = "world"
    COLUMN = "column"
    BARRIER = "barrier"
    BASE_POINT = "base_point"
    SUPERSTRUCTURE = "superstructure"
    SUBSTRUCTURE = "substructure"
    COORDS = "coords"
    SLAB = "slab"

